name: Publish to NuGet
on:
  push:
    branches:
      - master # Default release branch
      - feature/nuget-publish
    pull_request:
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: dotnet build
      - name: test
        env:
          IGDB_API_KEY: ${{ secrets.IGDB_API_KEY }}
        run: dotnet test
  publish:
    # Only run this job on master
    if: github.ref == 'refs/heads/master'
    
    name: Publish to NuGet
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/checkout@v2
      
      # Publish
      - name: publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/IgdbDotNet/IgdbDotNet.csproj # Relative to repository root
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key